#Casadora

title: Nhi Tran

# Header
menu:
   Casadora: /
   The Company: /Company
   The People: /People
   Hospitality: /Hospitality
   Services: /Services
   The Works: /Works
   Contact: /#contact-form
# # Favicon
# homepage:
#    intro: images/homnepage/
#    what-i've-done-1: images/favicon-32x32.png
#    apple_touch_icon: images/android-chrome-192x192.png
#    safari_pinned_tab:
#    android_manifest: images/manifest.json
#    ms_browserconfig: images/browserconfig.xml
